### ISSUE TITLE
SQL-Template wird beim Import nicht angezeigt

### ISSUE THREAD

**Issue by contaoacademy** [contao/official-demo#101]
Problem besteht mit Contao 4.11.3

Nach der Installation der Demo wird über das Installtool kein Template zum Import angezeigt.

**Workaround:**
Aktuell habe ich die `official-demo-for-contao-4.11.1.sql` manuell nach `/templates` kopiert.
Der Import hat anschließend fehlerfrei funktioniert.

**Comment by cliffparnitzky** [comment]
Kann ich in meinem System leider nicht nachstellen. Kannst du die Erweiterung nochmal deinstallieren und neu installieren und schauen, ob irgendwie eine Info in der Konsole kommt?

**Comment by contaoacademy** [comment]
@cliffparnitzky
Ich habe noch mal eine komplett frische Contao 4.11.3 aufgesetzt und die Demo per Contao Manager hinzugefügt. Leider erscheint das Template trotzdem noch nicht. Auch ein Leeren des Cache brachte keine Änderung.

Fehlermeldungen oder Meldungen im Log oder der Konsole konnte ich auch nicht finden.

**Comment by cliffparnitzky** [comment]
Hmmm, kann es am Hosting liegen? Hast du zufällig ein alternativ anderes Hosting zum Testen?

**Comment by contaoacademy** [comment]
Ich teste später mal lokal und auf einem alternativen Hosting.

**Comment by contaoacademy** [comment]
Auch Lokal mit MAMP Pro dasselbe Problem. Ich könnte jetzt noch einen alternativen Hoster testen, doch ich glaube nicht, dass das wirklich etwas ändert. 
Wie kann ich helfen das Problem zu analysieren?

**Comment by cliffparnitzky** [comment]
Ich hab ehrlich gesagt keine Ahnung. @Toflar hats du vlt. eine Idee, warum die Datei via Composer nicht korrekt im `templates` Ordner abgelegt wird?

**Comment by mlwebworker** [comment]
Ich wollte gerade mal schauen, ob das in der LTS-Version funktioniert, aber da lässt sich die Demo gar nicht installieren. Für mich zwar kein Problem, aber ideal finde ich das auch nicht, falls mal jemand Contao mit der Demo und LTS-Version testen möchte.

**Comment by cliffparnitzky** [comment]
> Ich wollte gerade mal schauen, ob das in der LTS-Version funktioniert, aber da lässt sich die Demo gar nicht installieren.

@mlwebworker Für die 4.9 muss das 4.5 installiert werden. Hast du die probiert?

**Comment by cliffparnitzky** [comment]
@contaoacademy Bist du auch bei Hostingwerk?

**Comment by contaoacademy** [comment]
@cliffparnitzky Mein Test war bei All-Inkl. Ich könnte aber auch mit Hostingwerk testen.

**Comment by cliffparnitzky** [comment]
@contaoacademy Ja, teste mal bitte. Kann nicht schaden.

**Comment by fritzmg** [comment]
The Problem is here: https://github.com/contao/official-demo/blob/832cf7d25e19bb36decfede7557cb038bb6d7ccd/composer.json#L6-L8

The `contao-community-alliance/composer-plugin` is missing from the dependencies. That explains why it is still working in some installations. But it won't work in a completely clean Contao installation.

**Comment by fritzmg** [comment]
Something has gone awry with this repository anyway. The new default branch is `main`, but the current `4.11.0` release tag is still based on `master`. `master` should probably be merged into `main` and then deleted.

**Comment by mlwebworker** [comment]
@cliffparnitzky @contaoacademy
Mit Hostingwerk hatte ich getestet.

**Comment by mlwebworker** [comment]
@cliffparnitzky Nein hatte bei der 4.9 nur ganz normal die Demo als Paket im Manager gesucht und versucht zu installieren, so wie das wahrscheinlich jeder normale Nutzer auch tun würde. Ich finde dabei sollte die Demo installierbar sein ohne irgendwelche "Umwege", die man gehen könnte. Wer Contao mit einer eigenen Installation testen möchte, sollte möglichst ohne irgendwelche Schwierigkeiten die neueste Version und eine LTS verwenden können - meine Meinung. Ist aber zu dem Thema etwas OffTopic.
Werde nacher noch die 4.5 testen.

**Comment by cliffparnitzky** [comment]
@mlwebworker Das ist leider nicht möglich, weil die DB Strukturen zwischen 4.9 und 4.11 ja anders sind. Und dass Composer erstmal die neueste Version anbietet, ist ja leider Tatsache. Da kann man nicht viel machen. Aber um das visuell etwas hervorzuheben ist ja nun die Major und Minor Version der Demo im Gleichklang zum Contao Core.

**Comment by mlwebworker** [comment]
Die 4.5 funktioniert mit Contao 4.9

**Comment by contaoacademy** [comment]
Ich habe wie von @fritzmg vorgeschlagen jetzt mal in die composer.json die nötige Abhängigkeit eingetragen.
Jetzt hat alles funktioniert.
`"contao-community-alliance/composer-plugin": "^3.2"`

@cliffparnitzky 
Kannst du das mal in der Demo als Abhängigkeit hinzufügen?

**Comment by fritzmg** [comment]
The branches should be fixed first though.

**Comment by cliffparnitzky** [comment]
@contaoacademy Probiere mal bitte mit der Version [4.11.1](https://github.com/contao/official-demo/releases/tag/4.11.1)

**Comment by cliffparnitzky** [comment]
Dann machen wir das Ticket hier zu. Danke an alle Beteiligten.
