### ISSUE TITLE
Implement sass and compass support

### ISSUE THREAD

**Issue by may17** [contao/official-demo#2]
Contao 3.3 ships with sass and compass support. This feature should be represented in the contao demo.

**Comment by may17** [comment]
We decided to drop the Stylesheet Database Support with contao 3.5. So Scss files will be the future of the contao demo.

**Comment by MoniqueHahnefeld** [comment]
Hey @may17 Joe.
ich habe jetzt angefangen ein SCSS-bundle zu erarbeiten und werde bis Ende nächster Woche damit fertig sein. Habt ihr auch schon begonnen. Vielleicht kann man sich da absprechen?

**Comment by Samuelll** [comment]
Hallo Monique,
ich habe schon etwas erstellt und bin damit recht weit fortgeschritten.
Wenn wir also unnötige Arbeit vermeiden wollen, sollten wir uns
unbedingt absprechen.

Gruß,
Sascha

Am 10.07.2015 um 18:07 schrieb Monique Hahnefeld:

**Comment by MoniqueHahnefeld** [comment]
Ok, kann ich dich morgen Nachmittag dazu mal anrufen?

**Comment by MoniqueHahnefeld** [comment]
Sascha und Ich haben eben unsere beiden Varianten besprochen und werden beide zur Verfügung stellen und nächste Woche diskutieren wie der Aufbau der Variablen under Ordner-Struktur sein sollte.

Eure Meinung ist herzlich willkommen @may17 und @allother :)

@Samuelll hier siehst du wie Bootstrap das macht:
https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L397
Die gehen auch den Weg über detaillierte Benennung nach Komponenten.

**Comment by may17** [comment]
Klar können wir gerne besprechen. Bitte vergesst aber nicht, dass die Demo so flach wie möglich gehalten werden soll. Ich finde Ansätze wie von dir @MoniqueHahnefeld sehr gut aber das Ziel der Demo ist es einfach zu sein ausgehend vom eher unerfahrenen Anwender.

Eine Konvertierung der jetzigen Demo Css samt der Variablen ist für den ersten Schritt vollkommen ausreichend. Zu dem wäre eine Sass Grid implementierung für Contao generell wichtig ebenso wie ein prozentuales Grid.

**Comment by MoniqueHahnefeld** [comment]
@Samuelll Du wolltest deine Version, was du schon hast auch hochladen. Wann wirst du das tun :) ?
Ich würde gerne einen Konsens finden worauf wir da aufbauen können, was die Struktur angeht.

**Comment by MoniqueHahnefeld** [comment]
@may17 
"Eine Konvertierung der jetzigen Demo Css samt der Variablen ist für den ersten Schritt vollkommen ausreichend. Zu dem wäre eine Sass Grid implementierung für Contao generell wichtig ebenso wie ein prozentuales Grid." -> warum nicht mehr, wenn es schon gemacht ist? Ich sehe hier den Sinn nicht.
Würdest du mit einer unvollständig durchdachten SCSS-Variante arbeiten wollen?

**Comment by Samuelll** [comment]
Die Files sind schon seit 14. fertig.
Scheint als hab ich das mit github noch nicht so im griff :-/

Am 20.07.2015 um 14:09 schrieb Monique Hahnefeld:

**Comment by MoniqueHahnefeld** [comment]
@Samuelll kannst du nicht einfach ein PR machen wir ich auch oder ein Fork und den Hier verlinken?

**Comment by may17** [comment]
@MoniqueHahnefeld es geht bei der COD nicht darum einen Startpunkt für das erste eigene Projekt zu haben. Die Demo ist zum testen und rumspielen da was anderes gibt die Lizenz gar nicht her da shareAlike ;) Daher "keep it simple and stupid".

**Comment by MoniqueHahnefeld** [comment]
@may17 Also @Samuelll war auch der Meinung das eine SCSS-Variante angebracht ist. Ich versteh deinen Ansatz ehrlich gesagt überhaupt nicht. @leofeyer Hat die Letzte Music Academy auch als SCSS-Variante gebracht. Und damit kann man auch besser herumspielen und lernen.

**Comment by Samuelll** [comment]
@MoniqueHahnefeld Eine SCSS-Variante stand auch nie in Frage.
Lediglich bei der Tiefe der Ausgestaltung seit Ihr nicht einer Meinung.

Ich bin mir selbst noch nicht sicher wie tief diese gehen soll, kann mir aber durchaus vorstellen, dass einige nicht so erfahrene Interessenten auf der Strecke bleiben, wenn man alle SCSS-Register zieht.

**Comment by MoniqueHahnefeld** [comment]
@Samuell Ja ich habe das ja verstanden das meine Variante vielleicht zu komplex für einen Anfänger ist. Ich finde es aber wenig konstruktiv wenn man einfach pauschal sag: "Das nehmen wir so nicht"
Wir können doch hier eine sinnvolle Struktur diskutieren und uns darauf dann festlegen. Ein SCSS-Package nützt finde ich nix wenn die Struktur nicht gut ist. 

Ich wollte gerne was mit meinen SCSS Erfahrungen zum Projekt beitragen. BTW: Hast du deine Variante denn jetzt hochgeladen bekommen?

**Comment by Samuelll** [comment]
@MoniqueHahnefeld Ohne jetzt genau nachzulesen hab ich nicht "Das nehmen wir so nicht" verstanden. Eher habe ich was von "sehr guten Ansätzen" in Erinnerung.

Eine sinnvolle Struktur ist Projekt- und Geschmacksabhängig.
Ich habe aktuell gerade ein spannendes Projekt wo ich wieder eine andere Ordner - und Dateistruktur vorfinde, als ich sie bisher gesehen oder genutzt habe. Gute Struktur definiert einfach jeder anders.

Für die COD habe ich versucht Sie ziemlich einfach zu halten.
Das Ergebnis findest Du hier:
https://github.com/contao/official-demo/tree/master/src/files/contaodemo/scss

Was ich als nächste größere Schritte für sinnvoll erachte ist der Austausch des Grids, wie es auch bereits in einem der Tickets angedacht wurde.
Danach wäre es aus meiner Sicht sinnig das CSS einem Rewrite zu unterziehen und damit gern auch die Datei- und Ordnerstruktur zu überarbeiten.

Deine Unterstützung ist uns weiterhin willkommen.

**Comment by may17** [comment]
@MoniqueHahnefeld ich habe in keinem Satz gesagt "Das nehmen wir so nicht". Das ist schlicht eine Unterstellung.

Ich verstehe noch nicht genau was deine Mission gerade ist? Ich habe eher das Gefühl, dass es dir darum geht die COD so zu verändern wie es dir passt. So funktioniert das aber nicht. Wenn du dich in die COD einbringen willst wäre es sinnvoll das Gespräch mit den beteiligten zu Suchen anstelle hier wilde Diskussionen anzufangen oder dein eigenes Ding durchzuziehen.

**Comment by MoniqueHahnefeld** [comment]
@may17 Nein das verstehst du falsch. Ich warte nur seit dem PR mal auf ein konkretes Feedback. Sowas wie: Die Variablen übernehmen wir. Oder die Ordner sind auf jeden Fall sinnvoll. Einfach damit es weiter geht. Entschuldige wenn ich da etwas ungeduldig bin. Und ich wüsste jetzt auch nicht warum wir das nicht hier ausdiskutieren können. Dafür sind doch die Tickets und es kann so jeder seine Meinung dazu geben, oder etwa nicht?

**Comment by may17** [comment]
Ich wüsste nicht über was es zu diskutieren gibt. Dieses Ticket hat nichts mit deinem Pull request zu tun. Du musst dich wohl oder übel gedulden.
