### ISSUE TITLE
Seite media-elements.html funktioniert nicht in online Demo

### ISSUE THREAD

**Issue by BugBuster1701** [contao/official-demo#26]
Grund ist das Element mit dem Youtube Video, dort ist nach Reset der Seite ein Template ce_player_responsive ausgewählt.
Dieses kann nicht geladen werden, da im Layout das Templateverzeichnis nicht ausgewählt ist und auch nicht ausgewählt werden kann.

**Comment by Aybee** [comment]
Die Seite https://demo.contao.org/en/media-elements.html konnte eben nicht aufgerufen werden - Fehlermeldung im FE. Es liegt an dem Videoelement. Dieses hatte kein Template ausgewählt. Ich habe dann das Core-Template ausgewählt und gespeichert. Dann lief die Seite wieder.

Dann wollte ich den Fehler wieder provozieren und habe das Template wieder abgewählt - FE lief seltsamerweise immer noch.

Dann habe ich die erste CE-Version wiederhergestellt und der Fehler war wieder da.

Wenn sich das mal jemand anschauen könnte? Danke.

**Comment by cliffparnitzky** [comment]
Hmm, also ich kann auch meinen 3 Testsystem den Fehler nicht erzeugen.

Allerdings sehe ich, dass die Konfiguration genau diese Youtube Elements nicht korrekt vom SQL in Contao ankommt. Grundsätzlich sollte dem Youtube Element das Template `ce_player_responsive` zugewiesen sein. Man kann das im BE aber nur im Info Popup sehen, weil das Select in der Edit Maske den Namen nicht zulässt. Insofern denke ich, dass dies nicht ganz korrekt ist, bzw. umbenannt werden müsste.

Trotzdem führt das in meinen System nicht zu dem Fehler.

In der Online Demo ist aber im Menü der Punkt "Template" entfernt. Wie auch immer das hier passiert. Wenn man den Templates Ordner im Theme wählen will, sieht man `templates/contaodemo` nicht. Das Info Popup des Theme zeigt das aber korrekt an.

Ich fasse mal zusammen:

1. die Konfiguration des Youtube Elements / Templates muss angepasst werden
2. ob 1. den Fehler behebt ist fraglich

@leofeyer Was sagt denn das Log zu diesem Seitenaufruf?

**Comment by Aybee** [comment]
> Hmm, also ich kann auch meinen 3 Testsystem den Fehler nicht erzeugen.

Aber du siehst den Fehler, wenn du meinen Link anklickst, oder?

**Comment by cliffparnitzky** [comment]
japp, sehe ich. Aber hier siehst du ihn nicht: http://contao46x.contao.cliff-parnitzky.de/media-elements.html

**Comment by cliffparnitzky** [comment]
Ich schließe diese Ticket, da das Problem nun nicht mehr in der Demo vorhanden ist.
