### ISSUE TITLE
Farbgestaltung ändern

### ISSUE THREAD

**Issue by Aybee** [contao/official-demo#35]
Vielleicht kann der ursprüngliche Designer (er wurde irgendwo mal erwähnt und ihm für seine Arbeit gedankt, ich kann mich aber nicht mehr daran erinnern wer es war) das Farbkonzept nochmal überdenken. Ich finde diese Brauntöne irgendwie sehr schmutzig und gar nicht schön.

Ich könnte mir vorstellen, dass da sogar ganz einache Grauwerte viel mehr Frische reinbringen würden als diese Graubraun-Farbnuancen. Ich bin kein Designer und kann nur meinen Eindruck schildern, aber vielleicht stehe ich mit dem Eindruck ja nicht alleine da.

**Comment by may17** [comment]
Farbvariablen sind jetzt drin. Leo, sascha und ich haben beschlossen das ab Contao 3.5 die Demo nur noch mit scss/less files ausgeliefert wird. Wir werden das dann berücksichtigen mit der Farbanpassung.
