### ISSUE TITLE
Padding in table cells th and td

### ISSUE THREAD

**Issue by Aybee** [contao/official-demo#41]
Das Padding von **1%** auf den Tabellenzellen ist nicht so gut. Das heißt, das Padding reguliert sich nach der Größe der Tabellenzelle. https://github.com/contao/official-demo/blob/master/src/files/contaodemo/theme/css/ce.css#L102

Es wird irgendwie nicht richtig berechnet, wenn eine Tabelle eine feste Breite oder width:auto; hat.

Mir ist es hierbei aufgefallen. Bitte mal dieses ce_table
```html
<div class="ce_table block">
  <h3>Example</h3>
  <table id="table_279" style="width:auto;">
    <thead>
      <tr>
        <th class="head_0 col_first">Head 1</th>
        <th class="head_1">Head 2</th>
        <th class="head_2 col_last">Head 3</th>
      </tr>
    </thead>
    <tbody>
      <tr class="row_0 row_first even">
        <td class="col_0 col_first">ColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn</td>
        <td class="col_1">Column 2</td>
        <td class="col_2 col_last">Column 3</td>
      </tr>
      <tr class="row_1 odd">
        <td class="col_0 col_first">Column 1</td>
        <td class="col_1">Column 2</td>
        <td class="col_2 col_last">Column 3</td>
      </tr>
      <tr class="row_2 row_last even">
        <td class="col_0 col_first">Column 1</td>
        <td class="col_1">Column 2</td>
        <td class="col_2 col_last">Column 3</td>
      </tr>
    </tbody>
  </table>
</div>
```
hier einfügen http://demo.contao.org/en/text-elements.html#table_279 (mit Firebug)

Ich habe nur die Tabellenbreite auf **auto** gestellt und im ersten TD einen Text eingefügt, welcher nicht umbrechen kann.

Ein Padding von sagen wir mal ".5em" würde keine Probleme bereiten und ich denke auch, dass das Padding sich eher an der Schriftgröße anstatt der Zellengröße orientieren sollte.

*btw THs und TDs sollten meiner Meinung nach default vertical-align:top; bekommen.*

**Comment by may17** [comment]
vertical-align:top; ist hinzugefügt und die paddings sind nun auf px werte umgestellt.
