### ISSUE TITLE
COD-Installation mittels Composer

### ISSUE THREAD

**Issue by xchs** [contao/official-demo#48]
Seit dem letzten (?) Release lässt sich die COD offenbar nicht mehr mittels Composer installieren.

Nach Installation des Contao Cores (3.4.3) über
```console
$ php composer.phar install --prefer-dist
```
hatte ich die Demo-Daten bislang immer mittels
```console
 $ php composer.phar require contao/official-demo:dev-master
```
angefordert, was stets problemlos funktioniert hat.

Nun erhalte ich aber die folgende Meldung und die Installation bricht ab:
```console
$ php composer.phar require contao/official-demo:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for contao/core 1.0.0 -> satisfiable by contao/core[1.0.0].
    - contao/official-demo dev-master requires contao/core 3.4.* -> satisfiable by contao/core[3.4.0, 3.4.1, 3.4.2, 3.4.3].
    - Can only install one of: contao/core[3.4.0, 1.0.0].
    - Can only install one of: contao/core[3.4.1, 1.0.0].
    - Can only install one of: contao/core[3.4.2, 1.0.0].
    - Can only install one of: contao/core[3.4.3, 1.0.0].
    - Installation request for contao/official-demo dev-master -> satisfiable by contao/official-demo[dev-master].


Installation failed, reverting ./composer.json to its original content.
```

Hängt das irgendwie mit #47 bzw. 7669a0c814cc3b54090d84e2dd710685290c2268 zusammen?

**Comment by discordier** [comment]
@xchs Bitte mal die kompletten dependencies posten.

**Comment by xchs** [comment]
@discordier 

Die `composer.json` ist jene aus dem Core: https://github.com/contao/core/blob/master/composer.json

Über die Kommandozeile rufe ich dann
```console
 $ php composer.phar require contao/official-demo:dev-master
```
auf, wodurch im `require`-Objekt zusätzlich die Eigenschaft
```json
"contao/official-demo": "dev-master"
```
ergänzt wird.

Nachdem die Abhängigkeiten aber nicht aufgelöst werden können, wird dieser Eintrag automatisch wieder entfernt und die `composer.json` auf den ursprünglichen Zustand zurückgesetzt.

Die Installation des Pakets "[dev-contao-3.4.0](https://packagist.org/packages/contao/official-demo#dev-contao-3.4.0)" funktioniert hingegen ohne Probleme; aber da gibt es die mit #47 eingeführte Abhängigkeit vom Contao Core auch noch nicht.

Aber vielleicht mache ich da auch nur grundsätzlich irgendetwas falsch oder ich verstehe es einfach nicht richtig.

**Comment by discordier** [comment]
Du sollst auch nicht in der root composer.json requiren sondern entweder im backend composer-client oder aber im unterverzeichnis "composer" via command line.

Die root composer.json vom contao/core ist lediglich um die direkten dependencies von Contao zu tracken und ein dist archiv zu erzeugen. Unter Contao 3.X werden die Erweiterungen im isolated "TL_ROOT/composer" Verzeichnis abgelegt.

**Comment by xchs** [comment]
Danke, @discordier 

> Du sollst auch nicht in der root composer.json requiren sondern entweder im backend composer-client oder aber im unterverzeichnis "composer" via command line.

Über den Composer Client im Backend funktioniert es natürlich und auch das Anfordern der Contao Demo über die Kommandozeile klappt soweit, wenn ich – wie von Dir vorgeschlagen – die Abhängigkeit in der `./composer/composer.json` entsprechend um `contao/official-demo": "dev-master` ergänze.

Das Problem ist nur: Das Unterverzeichnis `TL_ROOT/composer` existiert erst dann, wenn der Composer Client (im Backend) installiert ist. Geplant war aber, die **ganze** Installation soweit wie möglich auf der Kommandozeile auszuführen, d. h. zunächst den Contao Core zu holen und gleich im Anschluss die Contao Official Demo. Letzteres ohne dafür erst ins Backend zu müssen.

Gibt es da eine andere Möglichkeit oder muss ich für die Installation der COD auf der Kommandozeile auf Composer verzichten und mir die Demo anderweitig holen?
