### ISSUE TITLE
COD v3.2.1 mit db von 3.4 im ER2

### ISSUE THREAD

**Issue by ciaobello** [contao/official-demo#51]
Ich habe versucht die Demo über das ER2 zu installieren für 3.2:

contao_v34_official-demo.sql

Der Import konnte nicht abgeschlossen werden! Ist die Datenbankstruktur aktuell und die Template-Datei kompatibel mit Ihrer Contao-Version?

Es scheint dass da eine falsche .sql im zip archiv ist?

**Comment by Samuelll** [comment]
Kann ich bestätigen.
Der Dump is aus der 3.4

**Comment by pedaworx** [comment]
https://github.com/contao/official-demo/tree/release/contao3.2/src/templates

@ Nicky danke für den Link

**Comment by frontendschlampe** [comment]
bitte fein :-)

**Comment by ciaobello** [comment]
Hat geklappt danke.

**Comment by may17** [comment]
Es gibt ein neues Release welches den Fehler behebt.
