### ISSUE TITLE
Wünsche für das Contao Grid

### ISSUE THREAD

**Issue by may17** [contao/official-demo#52]
Moin Moin,

Wir würden gerne das Grid von Contao modernisieren. Es gibt hier verschiedene Möglichkeiten und ich möchte gerne ein paar Meinungen dazu. Dieses Ticket hat nur indirekt mit der Demo zu tun da es einen Pull Request für den Contao Core geben wird. Wichtig ist das die Rückwärtskompatibilität berücksichtigt wird.

Variante a)
Neben der grid.css wird es eine grid1140.css Datei geben welche das bisherige Muster übernimmt nur halt breiter ist ist einen Breakpoint mehr hätte

Variante b)
Es gibt ein flexibeles Grid welches 12 Spalten als Prozent beinhaltet. Durch das Layout kann die breite dann selbst angegeben werden.

Variante c)
Wir lösen uns von den 12 Spalten und erstellen ein Konfigurierbares Grid auf Basis von SCSS. Die Demo für 3.5 wird so oder so nur noch über SCSS laufen. Wäre daher eine Option.

Bei Variante b) und c) bleibt die grid.css natürlich weiter bestehen.

Was meint ihr?

**Comment by fjacobi** [comment]
Ich würde für C stimmen. 
Als mitgebrachte Variante ermöglicht es einem die meisten Möglichkeiten.

**Comment by Samuelll** [comment]
Variante C --> +1

**Comment by Ainschy** [comment]
Variante C

**Comment by leofeyer** [comment]
Unabhängig von c) fände ich b) gut für den Core. Dort können wir nämlich nicht SCSS voraussetzen.

**Comment by Aybee** [comment]
C :+1: 
Eine Variante B (Prozent-Grid) sollte aber schon vorbereitet sein.

**Comment by MacKP** [comment]
Ich bin auch für dafür, das beides beigelegt wird: C mit B
Also: In scss wird gearbeitet. Davon werden dann CSS-Dateien (Unkomprimierte und nicht zusammengefasste) erzeugt. Beides wird zur Verfügung gestellt. Als Vorbild könnte man sich da Yaml anschauen (da wirds auch so gemacht). Vorteil ist: Ihr braucht nicht beides Pflegen, weil das CSS erzeugt wird. Der Endverbraucher kann sich aussuchen was er will. Und wenn man SCSS nutzt, dann kann man sich das Grid auch noch so anpassen wie man möchte.
Variante B wäre dann praktisch das default, was vorkonfiguriert ist vom Grid-System.

**Comment by medianetic** [comment]
Eindeutig C. Die anderen Varianten sind jetzt schon nicht mehr zeitgemäß. Gut wäre es auch eine editierbare visuelle Version fürs BE gleich mitzukalkulieren.

**Comment by Samuelll** [comment]
@medianetic: Der zweite Wunsche würde eine separate Extension bedeuten. 
Die COD wird aber generell ohne weitere Extensions ausgeliefert.

**Comment by may17** [comment]
Danke für den Input. Dann packen wir mal b) und c) als neue Features an :)
