### ISSUE TITLE
wrong links

### ISSUE THREAD

**Issue by Aybee** [contao/official-demo#53]
Die Links stimmen nichts mehr
http://demo.contao.org/en/
Unter dem Punkt "Learn more" z.B. der Link "Navigation". Sieht so aus als hätten sich die Seiten-IDs geändert und die Inhaltselemente davon nichts mitbekommen. Da steht immer noch `{{link_url::26}}` aktuell ist `{{link_url::63}}`

**Comment by Samuelll** [comment]
Ich schau mir das in den kommenden Tagen mal an und werd dann eine angepasste sql-Datei erstellen.

**Comment by may17** [comment]
@Samuelll wolltest du dir das nicht im März ansehen?

**Comment by may17** [comment]
Fixed auf der Startseite
