### ISSUE TITLE
Contao Demo im Backend auf Deutsch

### ISSUE THREAD

**Issue by Sascha07** [contao/official-demo#54]
Besteht die Möglichkeit die Contao-Demo -> http://demo.contao.org im Backend auch auf Deutsch einzustellen?

**Comment by Samuelll** [comment]
Nein, dort gibt es nur englisch als Sprache für den Benutzer.
So wird verhindert, dass die Tester Ihre Sprache einstellen und den Rest der Stunde für alle anderen anderen das Backend unverständlich ist. 
Hab schon öfter erlebt, dass jemand das BE nur zum Spaß auf Türkisch umgestellt hat.

**Comment by ciaobello** [comment]
Ich habe Sascha07 hierher geschickt mit dem Argument dass sich Leo hier öfters aufhällt als im Forum.
Ich schreibe mal mein [Vorschlag beim Core] (https://github.com/contao/core/issues/7720) rein.

Das Problem könnte man ganz einfach lösen indem man oben neben dem Loginname im BE auch die Sprache anzeigen würde:

User k.jones | Türkçe > Turkish
Und ein drop down Menu zum einstellen der installierten Sprachen. Ich zumindest würde so ein Srachwechsler oben Rechts bei einer Seite erwarten und nicht in einem Userprofil.

**Comment by Aybee** [comment]
:-1:  
Es ist üblich, dass man in einem System in welches man sich eingeloggt hat zuerst in die Einstellungen geht und sich seine Sprache einstellt. Es wäre ein unnötiges, großes Selectfeld auf jeder BE-Seite. Dass die Sprache in der Demo erstmal auf Englisch gelockt ist finde ich gut. Es würde höhstens für die Demo Sinn machen die Benutzersprach auf User-Ebene in einem Cookie zu speichern.
> nur zum Spaß auf Türkisch umgestellt hat.

Ja, der konnte bestimmt nur Türkisch und hatte seinen Spaß dabei ;)

**Comment by may17** [comment]
Dieses Ticket hat nichts mit der Entwicklung der contao Demo zu tun. Die Demo auf Contao.org wird von leo zu Verfügung gestellt.
