### ISSUE TITLE
Navigation Level 2 springt zurück auf Level 1

### ISSUE THREAD

**Issue by peter67** [contao/official-demo#55]
Tablet: Android (Portrait und Landscape)
Hauptnavigation (oben), Navigation in linker Spalte wird nicht benutzt!

Touch auf "Content Elements"
Touch auf "Accordion"
Touch auf "Content Elements", um dropdown wieder zu öffnen und zu "Content slider" zu gelangen.
Die Navigation springt, nach kurzem Öffnen des dropdowns, wieder auf "Content Elements".
Erst dann kann man den nächsten Level 2 Punkt anwählen.

Gruß Peter

**Comment by ciaobello** [comment]
Aber die Seite wechselt nicht oder? Ich kann bestätigen dass Content Elements Aktiv ist, aber auch Accordeon ist aktiviert. Dies wird aber angezeigt weil es eine Unterseite von Content Elements ist!

Bestätige bitte ob die Seite Wechselt oder nur die Anzeige beim Menu, dazu wäre noch wichtig mit welchem Browser du das Problem hast.

Ich habe es mit einem Android 4.4.4 Handy getestet (Portrait & Landscape) mit aktuellem Chrome Browser.

**Comment by peter67** [comment]
Ich habe jetzt den aktuellen Chrome benutzt. Bei der Tablet-Größe ist oben das Hauptmenü mit den 4 Menüpunkten zu sehen, in der linken Spalte das Submenü, das nicht! benutzt wird.
Ich klicke auf "Content Elements" und es lädt die richtige Seite. Das Klappmenü schließt sich wieder.
Ich klicke wieder auf "Content Elements", um im ausgeklappten Menü auf "Accordion" zu klicken.
In dem Moment klappt das Menü wieder zu.
Wenn man schnell ist, kann man gerade noch "Accordion" anklicken, dann geht es manchmal und man landet bei Accordion. Manchmal landet man auch bei "Content Elements".
Es hängt also von der Schnelligkeit ab, ob die Seite wechselt - zumindest beim Chrome.

Bei Nutzung des von Android mitgelieferten Browsers trifft meine erste Beschreibung zu. Da wechselt, von Accordion kommend, die Seite auf Content Elements, obwohl der Touch auf Content slider erfolgte.

**Comment by ciaobello** [comment]
Jetzt wäre noch interessant zu wissen welche Android Version und welche Auflösung resp. Pixelbreite vom Viewport du verwendest.
Für mobile Geräte ist es angebracht auch die Mobile Navigation zu verwenden. Denn diese Funktioniert.

**Comment by peter67** [comment]
Mann, Du machst es aber spannend ;-)
Das ist ein Medion Lifetab mit 1280x800 Bildpunkten und Android 4.2 Jelly Bean.
Auf meinem Hany habe ich auch gar kein Problem, da dort das andere Menü angezeigt wird. Aber dieses Tablet nimmt eben die mittlere Version, die zwischen 768 und 979 aufgerufen wird (responsive768-979.css). Das ist also die Normalversion der Navigation, die in der css-Datei nur hinsichtlich der Schriftgröße verändert wird.

**Comment by Samuelll** [comment]
Hallo Peter67,
hab das ganze gerade auf Android 4.4.2 mit einem Chrome getestet und
kann es leider nicht reproduzieren.

WEnn ich auf "Content Elements" bin ud nochmal auf den Punkt klicke,
bleibt die Unternavigation bei mir geöffnet.

Gruß,
Samuell

Am 10.05.2015 um 17:26 schrieb peter67:

**Comment by peter67** [comment]
Hallo Samuell,
ich bin auf "Content Elements" und *tippe* noch einmal auf den Punkt. Das Untermenü öffnet sich und schließt sich wieder sofort.
Am normalen Monitor, zusammengeschoben auf die entsprechende Bildschirmgröße, *klicke* ich auf den Punkt und das Menü bleibt geöffnet.
Es hat also etwas mit der touch-Funktion zu tun. Bei meinem Freund, der es mit zwei verschiedenen Geräten ausprobiert hat, ist es genauso.

Gruß
Peter

**Comment by Samuelll** [comment]
Hallo Peter,
ich hab es auf eine Note 10.1 getestet, also auch getippt und nicht
geklickt. Daher ist es zumindest mit meiner Technik nicht reproduzierbar.

Ein weiterer Test mit einem Galaxy Tag 3 8" brachte das gleiche
Ergebnis. Nicht reproduizerbar für mich.

Gruß,
Samuell

Am 10.05.2015 um 20:57 schrieb peter67:

**Comment by ciaobello** [comment]
Vielleicht könnte man als Anregung den Switch zum Mobilen Menü einbauen, dass auch Ultragrosse Tablets davon profitieren können. 
Ich kann es schlichtweg auch nicht nachvollziehen weil mein Samsung Galaxy keine solchen Auflösungen hat und nicht eine ältere Android Version verwendet.
Wenn Ihr also die Demo als Vorlage für Eure Seite verwendet baut den Switch {{toggle_view}} ein oder Stellt den Veiwport so ein dass bei mobilen Geräten immer das Mobile Menü angesprochen wird.

**Comment by peter67** [comment]
Vielen Dank für das Testen. Es bleibt also ein Rätsel.
Und, ja, wir können das natürlich anders lösen. Aber ich wollte einfach den festgestellten Fehler melden, damit der korrigiert werden kann.
Eine schöne Woche
Peter
