### ISSUE TITLE
use the same units in the stylesheets [enhancement][3.5]

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [contao/official-demo#56]
do not mix %, px and em for margin and padding. 
-> fix % with box-sizing if width is given in % value
do not mix px and em for font declarations

**Comment by may17** [comment]
Some examples would be nice.

**Comment by MoniqueHahnefeld** [comment]
Look into the css files :)

**Comment by Aybee** [comment]
Different values can have reasons. You can not say "don't mix values" across-the-board.

**Comment by MoniqueHahnefeld** [comment]
@Aybee Yes but there are much parts where I can not see a reason for it. The next time I'll post it with example.

**Comment by Aybee** [comment]
Yes please, example is necessary.

**Comment by Aybee** [comment]
For example: Padding values with % unit get computed by the width of the parent element. http://jsfiddle.net/Andreas/ehLukfoz/ You can't do that with REM or EM.

**Comment by MoniqueHahnefeld** [comment]
@Aybee Such case I have never needed in my 12 years css experience :) Every Designer I know prefers absolute value for padding or margin (e.g. in px).
In past box-sizing didn't exist. IE 8 and lower doesn't support it. In this cases you needed it for fluid grid.
But at the moment you can mix px/em/rem and %. That's no problem. And this theme does not support IE 8 so far.

**Comment by Aybee** [comment]
It was just an example. It's used by flowplayer to generate a box with for example 16:9 format without setting a height.

At least for paragraphs designers should set spacing according to font-size. Also in other situations designers should think about if it's appropriate to use values that adapts oneself to the users browser font-size settings or the actual font-size settings of elements.

Core functionality should never support IE8. This can be done by extra programming for this very rare situations or special companys.

**Comment by MoniqueHahnefeld** [comment]
>At least for paragraphs designers should set spacing according to font-size. Also in other situations designers should think about if it's appropriate to use values that adapts oneself to the users browser font-size settings or the actual font-size settings of elements.

>Core functionality should never support IE8. This can be done by extra programming for this very rare situations or special companys.

@Aybee Yes, there you are right :) +1
