### ISSUE TITLE
remove double declaration in stylesheets

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [contao/official-demo#57]

**Comment by may17** [comment]
It would be nice to get some examples :) This ticket is at the moment not really helpful.

**Comment by MoniqueHahnefeld** [comment]
yes I found some here and there and droped them in my version into the scss files. sorry :)

**Comment by may17** [comment]
@MoniqueHahnefeld it dosen`t help the COD project if you create tickets with the answer "I fixed in my version" without any way to reproduce it. We have to fix it in the current css too.

**Comment by MoniqueHahnefeld** [comment]
@may17 I would like to help and add this ticket actually as proposal for enhancement. If help is unwished I will make my own stuff. Thx

**Comment by may17** [comment]
Please be honest, how helpful is a topic like "remove double declaration in stylesheets" without any description? Any help is welcome but as i said before, this tickets is not helpful without a pul request or problem descriptions.

**Comment by MoniqueHahnefeld** [comment]
@may17 It was thought as part of task in future, no direkt bug report. So someone could go through the stylesheets and looks for this double declaration. so you close it and its not done. ^^

**Comment by may17** [comment]
It´s not your job decide what we have to do in near feature. And as i said before. This kind of tickets aren`t helpful.

**Comment by MoniqueHahnefeld** [comment]
Ok, then I will ask you next time :)
