### ISSUE TITLE
responsive breakpoint styles?? 

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [contao/official-demo#59]
maybe it is better for maintaining to set the breakpoint-styles also in the component-file
>For example _slider.scss contains @media (){
 .slider{}
}

so the media declaration is douple but the overview is better I think.

What do you think @Samuelll, @may17

**Comment by may17** [comment]
Perhaps it`s better :) We talked a lot about this topic and decided to create just one media query file. I think it`s easier for beginners to have just one place for media queries.

**Comment by MoniqueHahnefeld** [comment]
ok I understand this.
