### ISSUE TITLE
Erweiterungskatalog: Autor = do_while

### ISSUE THREAD

**Issue by mathContao** [contao/official-demo#61]
Ich habe eben Contao 3.5.0 mit der Demo V 3.4.2 ausprobiert.

Im Erweiterungskatalog ist nach der Installation im Autoren-Filter "do_while" ausgewählt gewesen. War zu beginn etwas verwirrend, dass ich die gesuchten Erweiterungen nicht gefunden hatte.

Vorschlag: Autoren-Filter auf "Autor" setzen.

**Comment by Samuelll** [comment]
Danke für den Hinweis.

Am 18.07.2015 um 22:36 schrieb maTh:

**Comment by may17** [comment]
Fixed
