### ISSUE TITLE
Rand vom Contao-Logo sehr stufig

### ISSUE THREAD

**Issue by mathContao** [contao/official-demo#62]
Ich habe eigentlich nicht das Auge dafür, trotzdem fällt es mir auf: Der Rand des Contao-Logos im Slider ist sehr stufig. Betrachtet mit einem "normalen" Display (kein Retina).

![unbenannt](https://cloud.githubusercontent.com/assets/1645099/8763924/b3f561bc-2db5-11e5-9cb6-0d9ac3e8a985.JPG)

**Comment by Aybee** [comment]
Das Logo muss als Vektorgrafik gedreht werden und dann bereits in der richtigen Größe als PNG exportiert werden, dann hat man saubere Kanten.
![slider_big-c-new3](https://cloud.githubusercontent.com/assets/1143013/8768328/ffa93c84-2e7b-11e5-889f-42610367a7b8.png)
Das Bild könnt ihr benutzen, wenn ihr wollt. Ich habe das C gerade gestellt, aber die gleiche Größe und den gleichen Anschnitt habe ich auf die Schnelle nicht hinbekommen.
Geöffnet, gedreht und für Web gespeichert als PNG habe ich mit Illustrator gemacht, angeschnitten mit Photoshop.

**Comment by MoniqueHahnefeld** [comment]
+1

**Comment by may17** [comment]
+1 thx @Aybee

**Comment by sascha-mueller** [comment]
Bild ist getauscht.

**Comment by may17** [comment]
Thx. Allerdings wäre es besser wenn du die Änderungen im Develop Branch machst, da sonst die gefahr besteht das wir beim mergen für ein release nen alten stand reinholen.
