### ISSUE TITLE
Favicon fehlt

### ISSUE THREAD

**Issue by mathContao** [contao/official-demo#63]
Fehlt das Favicon bewusst?

Ich persönlich finde Webseite ohne Favicon "unvollständig". Die Wiedererkennung im Tab-"Wald" (bzw. Lesezeichenverwaltung) ist ohne Favicon nicht gegeben.

**Comment by MoniqueHahnefeld** [comment]
It's no Website, It's a Theme :)

**Comment by mathContao** [comment]
favicon is not a part of a theme?

**Comment by MoniqueHahnefeld** [comment]
I say only that a Theme is not a website ^^

**Comment by may17** [comment]
Das ist eine gute Frage ob ein Theme ein Favicon mitliefern sollte. Ich finde nicht das die Demo Theme unbedingt ein Favicon mitliefern muss. Was sagt denn die Mehrheit?

**Comment by Samuelll** [comment]
Muss nicht.
Wir wollen jedoch zeigen wie man eine Seite generell aufbauen kann, somit könnten wir auch zeigen wo ein Favicon eingesetzt werden sollte.

**Comment by may17** [comment]
Dann wäre ein Vorschlag zur Implementierung gut :)

**Comment by Samuelll** [comment]
Eine Vorlage für ein favicon erstellen 260px * 260px Format png
Den http://realfavicongenerator.net/ bemühen und das Ergebnis einbinden.
Dabei kommt der Code in das Feld des Layouts und die ca. 20 Grafiken die dabei entstehen in einen Ordner "files/contaodemo/theme/img/favicon".

**Comment by ciaobello** [comment]
Ich finde es nicht nötig dass eine Standard Installation ein Favicon braucht. Das erinnert mich schwer an Joomla, erkennt/erkannte man sofort mit welchem CMS die Seite erstellt wurde. Das ist dann schlimmer als kein Favicon. Dann verliert nämlich ein Favicon auch die Wirkung, dass man sofort erkennt um was für eine Seite es sich in der URL/Favoriten handelt.

**Comment by mathContao** [comment]
@ciaobello: Das Icon würde ja nur dann zu sehen sein, wenn die Demo-Webseite bewusst installiert wurde UND die Demo dann modifiziert und dann produktiv genutzt wird. Man wird dann wohl nicht nur das Favicon wiedererkennen, sondern auch weitere Gestaltungselemente.

Ich bin noch FÜR ein Favicon ;)

**Comment by may17** [comment]
Ok überzeugt. Also meinetwegen können wir ein favicon hinzufügen. Vielleicht auch gar nicht so schlecht als Beispiel wie man Favicons in Contao einbinden kann.

btw. wer die Demo Produktiv einsetzt sollte sich der Lizenz bewusst sein. Wenn die Demo für ein Kundenprojekt zur Verfügung gestellt wird muss das Projekt wieder unter die gleiche Lizenz gestellt werden was bedeutet das jeder sich an dem Projekt bedienen darf :)

Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

Quelle: https://creativecommons.org/licenses/by-sa/4.0/

**Comment by Samuelll** [comment]
Habe mir nun erlaubt wegen der Größe das Contao-Community Logo als Basis für die Favicons einzusetzen.
Über den Favicongenerator haben die Icons für Windows Phone und Appe leider nen Hintergrund.
Fühlt euch frei das ggf. noch zu korrigieren wenn Ihr etwas Zeit übrig habt. :-)

**Comment by Aybee** [comment]
Ich habe die Favs mal mit easyFavicon erzeugt https://contao.org/erweiterungsliste/view/easyFavicon.html. Die müssten eigentlich ohne Hintergrund sein.
Markup dazu:
```html
<link rel="shortcut icon" type="image/x-icon" href="http://demo.contao.org/share/favicon-contao-offical-demo.ico">
<link rel="apple-touch-icon" href="http://demo.contao.org/share/favicon-apple-touch-icon-contao-offical-demo.png">
```
![favicon-apple-touch-icon-contao-offical-demo](https://cloud.githubusercontent.com/assets/1143013/9983358/53850e06-5ff9-11e5-8ee1-9d043499cf4b.png)
![favicon-contao-offical-demo ico](https://cloud.githubusercontent.com/assets/1143013/9983359/5389a286-5ff9-11e5-8cab-3222867aadba.png)
Das kleine Bild ist das ICO, dieses bitte umbenennen von .png nach .ico. Upload ging hier nur als PNG.
