### ISSUE TITLE
Layout "2 columns" on page "Event Detail" is redundant

### ISSUE THREAD

**Issue by Aybee** [contao/official-demo#69]
Layoutzuweisung auf Seite Event Detail kann entfernt werden.

Und weil ich gerade den Screenshot hier habe und kein eigenes Ticket dafür aufmachen möchte: Diese Aliase können noch geändert werden:

1. My Account (account) => my-account
2. Logout (uer-logout) => logout
3. RSS Reader (rss) => rss ? Wenn der Alias hier auf rss stehen bleiben soll, könnte man den Seitennamen auch nach RSS ändern

Das Bunte sind die Layouts, Grau die Aliase, Grün die CSS-Klassen.
![seitenstruktur_-_contao_open_source_cms_3 5_-_2015-10-17_21 23 11](https://cloud.githubusercontent.com/assets/1143013/10560785/b1badd1c-7515-11e5-9008-dfa6279fa1ee.png)

**Comment by sascha-mueller** [comment]
@Aybee: Danke für die Hinweise. Werd mich dieser Dinge annehmen.

**Comment by may17** [comment]
@sascha-mueller  wo ist denn der commit zum Fix?

**Comment by sascha-mueller** [comment]
Wenn Du das auf den "close" beziehst, der war nicht beabsichtigt.
War mir garnicht bewußt, dass ich das Ticket geschlossen hatte.

**Comment by Aybee** [comment]
Zur schnellen Kontrolle kannst du die Dateien aus dieser ZIP in deinen ROOT schieben.
http://public.andreasburg.de/MyBE.zip

**Comment by sascha-mueller** [comment]
Das redundante layout hab ich entfernt.

Die beiden Seiten 
top-menu-folder/login/account
top-menu-folder/login/user-logout
waren ohne Inhalt und anscheinend auch nirgendwo verlinkt. 
Ich habe sie deshalb entfernt.

Bei der RSS-Seite empfinde ich den Titel als "Beschreibendes Element mit "RSS Reader" als korrekt.
Aus meiner Sicht ist der Alias hingegen mit "rss" korrekt benannt. Ich habe mich daher dazu entschlossen diesen nicht zu ändern.

**Comment by Aybee** [comment]
Ich danke dir. RSS könnte man evtl. RSS News(rss-news) benennen.

**Comment by sascha-mueller** [comment]
Ich bin immernoch mit der Benamung zufrieden, wie ich Sie oben beschrieben habe.
Sollten mehrere Leute damit nicht einverstanden sein, wär ich als nächstes dafür es einfach nur rss zu nennen.

**Comment by Aybee** [comment]
Ist ja auch nicht so wichtig, ist halt nur nicht konsistent. Mir als geborenem Kleinkrämer fällt es halt auf ;)

Die Seiten mit dem Newsreader und dem Eventreader heißen ja auch nicht "News Reader"... Und es gibt auch sonst keine Seiten, welche nach ihrem Haupt-Modul benannt sind. Und wenn sie doch "RSS Reader" heißt, was spricht hier dafür auf die Konsistenz zu verzichten und diese Seite als einzige nicht "rss-reader.html5" zu benennen. Technische Hintergründe?

**Comment by testbird** [comment]
Nur RSS scheint mir nicht eindeutig. Beim RSS Button rechts oben hatte ich z.B. erwartet das der RSS-Feed mit den News der Demo-Seite geoffnet wird. 

Was kam würde ich als "Contao Project News (RSS-Reader)" bezeichnen.
