### ISSUE TITLE
Event page with errorneous link

### ISSUE THREAD

**Issue by fritzmg** [contao/official-demo#73]
The "[Events](http://demo.contao.org/en/events.html)" page says the following:

> To see some actual calendar entries [click here to go to March 2013](http://demo.contao.org/en/events.html?month=201303).

However, there are no actual entries in March 2013.

**Comment by ciaobello** [comment]
> However, there are no actual entries in March 2013.

Its not march ... the Demo Data is in may 2013 ... so changing link to 
http://demo.contao.org/en/events.html?month=201305
solves the problem.
