### ISSUE TITLE
COD nach Contao 4.x portieren

### ISSUE THREAD

**Issue by sascha-mueller** [contao/official-demo#76]

**Comment by bezin** [comment]
Hallo Hallo,

wie ist denn da der Stand der Dinge und kann man hier unterstützen?

LG benzin

**Comment by sascha-mueller** [comment]
Hallo Benzin,
stand ist, dass wir erst mal einen sauberen Branch erstellen müssen, da ich wohl die Aktualisierungen in den falschen geschrieben habe.
Ich halte es für Sinnig danach die derzeit bekannten Fehler zu fixen, eine aktuelle Version für 3.5 zu veröffentlichen und auf Basis dieser eine Version für 4.x zu erstellen.

**Comment by Aybee** [comment]
Siehe auch hier:
[Forum: Contao 4 - COD - Contao Official Demo - Download ](https://community.contao.org/de/showthread.php?67049-Contao-default-Theme-quot-Music-Academy-quot&p=447691&viewfull=1#post447691)

Die ZIP enthält einen DB-Dump von Contao 4.4.2 mit COD und die Ressourcen aus files/ inkl. der geänderten _navigation.scss.

**Comment by Aybee** [comment]
Thank you Cliff 🥇

**Comment by may17** [comment]
Danke Cliff! Ich schau mir das an!
