### ISSUE TITLE
[BE][FileManager] Error on edit file

### ISSUE THREAD

**Issue by ADoebeling** [contao/official-demo#78]
If you try to edit a file within the filemanger you get an error:

![image](https://cloud.githubusercontent.com/assets/10674780/17178460/d79ad6f6-5415-11e6-8579-150d75d445a4.png)

**Comment by Aybee** [comment]
For security reasons this option is locked in the online demo. It will work in your own installation.

**Comment by ADoebeling** [comment]
Thanks for the feedback. I'm not sure, which of the following options could harm the demo-installation?

![image](https://cloud.githubusercontent.com/assets/10674780/17205648/2329b5ec-54ac-11e6-9ea0-2164251347d0.png)

**Comment by Aybee** [comment]
I only tested the editing of the files content.

Yes the editing of filename and meta data should not be a security risk.

Maybe the text "An error occurred!" can be changed to "Locked for security reasons in online demo!".
