### ISSUE TITLE
SASS can not compile variables in single quotes => add function

### ISSUE THREAD

**Issue by A-G-F** [contao/official-demo#79]
Microsoft CSS filters like
`filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='$navOffGradient1', endColorstr='$navOffGradient2',GradientType=0 );`
do not compile correctly.

For a solution see https://github.com/contao/official-demo/pull/68

**Comment by may17** [comment]
I am still waiting on a comment from @sascha-mueller because it`s his part and he created the sass stuff.

**Comment by sascha-mueller** [comment]
Lass uns den Pullrequest übernehmen.
Ich habe damals keine Probleme bei der Verwendung entdecken können, will aber nicht ausschließen, dass ich etwas übersehen habe.

**Comment by may17** [comment]
Done

**Comment by cliffparnitzky** [comment]
@may17 Kann das Ticket zu? Der PR #68 wurde ja gemerged.

**Comment by may17** [comment]
Ja kann zu. Ich schließe mal das Ticket.
