### ISSUE TITLE
Please set k.jones limitWidth to 1, like the default setting

### ISSUE THREAD

**Issue by Aybee** [contao/official-demo#81]
Ich ärgere mich jedesmal darüber, dass das Demo-BE in voller Breite angezeigt wird. Das macht es auf einem 27" Monitor mit 1920px Breite nicht einfach. Man muss den Kopf hin und her drehen um alles zu sehen, hat aber keinen Mehrwert, dass man z.B. weniger scrollen müsste oder mehr sehen würde (außer mehr Leerflächen und Farbe).

Selbst auf einem 15" Monitor würde ich mit 1920 Breite nicht mehr sehen, als mit diesen limitierten 1140px.

Ich denke diese volle Breite ist ein Gimmick für jemanden der es mag, 1140 ist aber benutzerfreundlicher.

Legt man einen neuen Benutzer an, hat der auch erstmal limitWidth = 1. Wohl aus den selben Gründen. Also wäre es sinnvoll, wenn man in der Online-Demo bei k.jones auch das Limit aktivieren würde.

**Comment by cliffparnitzky** [comment]
Da im Zuge der SQL Anpassung von #86 das Feld `limitWidth` entfernt wurde (nicht mehr in Contao 4.5) enthalten, kann dieses Ticket geschlossen werden.
