### ISSUE TITLE
Demo-Backend is broken

### ISSUE THREAD

**Issue by ADoebeling** [contao/official-demo#84]
Currently you can't login into the demo-backend:
https://drive.google.com/file/d/1mEmHjnY5K9T5DlOvzrhH6S8cPSeOnLJR/view

After loggin in you're getting redirected to `/ `with a `302 FOUND`.

**Comment by frontendschlampe** [comment]
no problem ... now it's working again. Maybe someone tried something and it goes wrong. After reset (every 10 min I think) everything is fine! ;-)

**Comment by ADoebeling** [comment]
@frontendschlampe Sorry, but I can't confirm. It still doesn't work.

**Comment by frontendschlampe** [comment]
hmmmm ... I tried with Safari, Firefox and Chrome on MacOS and I have no problems!

**Comment by ADoebeling** [comment]
Check at Windows 10 / Kabel Deutschland:
* Chrome: Error as described befor
* Chrome/private mode: Error as described befor
* Edge: Same error
* Firefox 56: Same error

Check at Windows 10 / Vodafone LTE: (without any Routers/Switches/Firewalls/...)
* Chrome/private mode: Same error
* Edge: Same error

![image](https://user-images.githubusercontent.com/10674780/36144637-f8742d58-10ae-11e8-9a16-837ddc899254.png)

**Comment by zonky2** [comment]
no problems with
* Chrome Version 64.0.3282.140 (Offizieller Build) (64-Bit)
* Win 7 Ultimate 64

**Comment by kikmedia** [comment]
Works for me (Windows 10, Chrome 64 and FF Quantum latest).

**Comment by Aybee** [comment]
A few days ago I wanted to show a customer the demo BE. I watched him by doing this with skype. He was not able to login, he always gets redirected to a page in the FE. Tested with FF58 and Chrome.

**Comment by may17** [comment]
This is an hosting issue on demo.contao.org not an official demo issue. You should report this on the contao/website issue tracker.
