### ISSUE TITLE
Nur Theme Import via Theme-Manager

### ISSUE THREAD

**Issue by fkaminski** [contao/official-demo#85]
Hallo,
eine Verständnisfrage. Wenn ich die Demo für die 4.4.x via Composer installiere werden die entsprechenden Datendateien installiert. Ich möchte nun aber NICHT im Anschluß über das Installtool das entsprechende Website-Template importieren. Vielmehr lediglich die Theme Einträge über den Contao Theme-Manager importieren. Eine entsprechende .cto Datei ist aber nicht vorhanden. Ist das systembedingt gewollt oder wie ist da die Vorgehensweise ...

**Comment by Aybee** [comment]
Da ist einfach keine CTO dabei. Die Komponenten des Themes kann man ja auch direkt in die DB schreiben und steht einfach in der SQL mit dabei. Du hast jetzt zwei Möglichkeiten.

1. Du modifizierst die SQL und schmeißt alle Tabellen raus, die du nicht importieren möchtest. Mach aber vorher ein DB Backup, weil dabei Datensätze überschrieben werden könnten, welche schon existieren.

2. Exportiere das Theme in der Online-Demo. Damit bekommst du eine CTO (das ist eine ZIP), welche du bei dir importieren kannst. Das ist vielleicht das Sicherste, weil Contao müsste dies ja managen, dass die IDs dabei richtig gesetzt werden. Wie genau Contao dies handhabt weiß ich nicht. Schau mal in der CTO in die theme.xml, dort stehen die Datensätze drin, welche nämlich auch bereits eine ID haben, aber das sollte von Contao richtig aufgelöst werden, falls es z.B. bereits ein Theme mit der ID 1 gibt. Mach also auch hier erstmal ein DB Backup.

**Comment by fkaminski** [comment]
Ok, 
Danke ...

**Comment by may17** [comment]
@fkaminski eigentlich war da immer eine cto Datei dabei. Die fehlt scheinbar beim 4er port. In der 3.5er war sie dabei siehe hier https://github.com/contao/official-demo/tree/develop/src/files/contaodemo

Das ist also ein bug!

**Comment by fkaminski** [comment]
> Ich bin dafür, dass die cto Datei zukünftig weggelassen wird. Welchen Nutzen soll die haben?

Na ja, ist wohl eine Grundsatzfrage bzw. ist selbstverständlich jedem Theme Anbieter überlassen wie was bereit gestellt wird. Wenn ein Theme ausschließlich den internen CSS Editor nutzt reicht die .sql aus - mögliche custom templates können zudem zuvor via Composer Plugin kopiert werden. 

Falls ein Theme (scss/css/js) auf externen Daten beruht hat man halt die Option lediglich das Theme an sich  - via .cto - inkl. custom templates zu importieren ohne die .sql - für Demo Inhalte - heranziehen zu müssen. Dafür ist es doch in Contao vorgesehen. 

So gesehen hat man aus meiner Sicht als Consumer eben eine Auswahl ...

**Comment by fkaminski** [comment]
Evtl. habe ich mich mißverständlich ausgedrückt. 
Über die aktuelle Vorgehensweise werden die Theme Daten ja via 

` 
"extra": {
"contao": {
            "sources": {
                "src/files/contaodemo": "files/contaodemo",
                "src/templates/codv4.2.0_contao_4.6.3.sql": "templates/codv4.2.0_contao_4.6.3.sql",
                "src/templates/contaodemo": "templates/contaodemo"
            }
        }
    }`

kopiert und es bleibt mir überlassen ob ich die Demo Daten via .sql nutze. Dazu ist halt aber eine Installation der Erweiterung erforderlich. Wenn eine .cto existiert könnte man auf eine Installation verzichten und lediglich die .cto laden und in Contao importieren ...

**Comment by cliffparnitzky** [comment]
Sehr verständlich erklärt. Vielen Dank. Ich packe die cto Datei in den nächsten Release.
