### ISSUE TITLE
Contao 4.6 requires error 401 pages

### ISSUE THREAD

**Issue by leofeyer** [contao/official-demo#87]
Contao 4.6 requires error 401 pages instead of error 403 pages to redirect unauthenticated users. The version 4.6 update automatically converts existing 403 pages to 401 pages, however, the current SQL dump still contains 403 pages.

**Comment by cliffparnitzky** [comment]
I'll check this and fix this soon.

**Comment by leofeyer** [comment]
Thanks 👍
