### ISSUE TITLE
Contao 4.7

### ISSUE THREAD

**Issue by Toflar** [contao/official-demo#91]
Not sure what exactly is your naming convention but here's a dump for 4.7 :-)

I also think you might want to delete the dumps of the unsupported Contao setups from `templates` because they are confusing in the install tool. If you want to keept them for reference, maybe just move them to some other folder but in `templates` we should only have 4.4 and 4.7 imho :)

[codv4.7.0.sql.zip](https://github.com/contao/official-demo/files/2876731/codv4.7.0.sql.zip)

**Comment by cliffparnitzky** [comment]
Ich hab die SQL Dateien mal in ein Archiv verschoben (siehe 39a6a6b6d8254d617763415725b1e2edacf576b1)

**Comment by cliffparnitzky** [comment]
Da die V 4.7 schon beendet ist schließe ich dieses Ticket und verweise auf #93
