### ISSUE TITLE
Contao 4.8 Kompatibilität herstellen

### ISSUE THREAD

**Issue by contaoacademy** [contao/official-demo#93]
Die Demo lässt sich nicht unter Contao 4.8 installieren.

**Comment by may17** [comment]
Ein paar mehr Details würden helfen. Ich nehme jetzt Mal an du meinst die Installation über das Installtool?

**Comment by contaoacademy** [comment]
@may17 Sorry, hier etwas mehr Details.

Ich wollte die Demo über den Contao Manager bei einer frischen Contao 4.8 Installation hinzufügen.
Inwieweit der Datenbank-Dump funktioniert kann ich nicht sagen, da ich so weit nicht gekommen bin.

**Comment by xchs** [comment]
Das Problem liegt hier in der `composer.json` (https://github.com/contao/official-demo/blob/master/composer.json#L7):
```json
...
"contao/core-bundle":"~4.6.4",
...
```
Der Versionsbereich wird dadurch auf >=4.6.4 und <4.7.0 beschränkt.

**Comment by contaoacademy** [comment]
> Der Versionsbereich wird dadurch auf >=4.6.4 und <4.7.0 beschränkt.

Ja und ggf. muss dann noch der DB-Dump aktualisiert werden.

**Comment by xchs** [comment]
Jup.

**Comment by Katze75** [comment]
Wann wird official-demo mit Contao 4.8 compatibel? Installation über das Installtool geht nicht :-(

**Comment by may17** [comment]
Ich bin leider derzeit recht beschäftigt. Vielleicht möchte ja jemand einen Pull Request erstellen?

**Comment by cliffparnitzky** [comment]
Version [4.3.0](https://github.com/contao/official-demo/releases/tag/4.3.0) ist für Contao >= 4.8.4 verfügbar.
