### ISSUE TITLE
Update for Contao 4.9

### ISSUE THREAD

**Issue by jochi44** [contao/official-demo#95]
**Description:**
Is there an updated version of the official-demo for the upcoming Contao V4.9 planned?

Installing the official-demo on a Contao 4.9.0-RC1 environment doesn't work:

`Your requirements could not be resolved to an installable set of packages. 
  Problem 1
    - Installation request for contao/official-demo ^4.3 -> satisfiable by contao/official-demo[4.3.0].
    - contao/official-demo 4.3.0 requires contao/core-bundle ~4.8.4 -> satisfiable by contao/core-bundle[4.8.4, 4.8.5, 4.8.6, 4.8.7, 4.8.x-dev] but these conflict with your requirements or minimum-stability.`

**Comment by cliffparnitzky** [comment]
Currently there no update explicitly planned ... but we need at least a stable Contao 4.9

**Comment by cliffparnitzky** [comment]
Die Version [4.4.0](https://github.com/contao/official-demo/releases/tag/4.4.0) kann nun ab Contao 4.9.1  installiert werden.
