### ISSUE TITLE
Login als Redakteur funktioniert nicht

### ISSUE THREAD

**Issue by contaoacademy** [contao/official-demo#97]
**Fehlerbeschreibung**

1. Contao Backend Login
https://demo.contao.org/contao

2. Login mit Benutzer `h.lewis`

3. Fehlermeldung
`Ungültiger Anfragetoken`

Ein Login mit k.jones funktioniert

**Comment by sascha-mueller** [comment]
Konntest Du das genau so mit einer selbst installierten Demo nachstellen?

Generell haben wir nämlich keine Möglichkeit auf https://demo.contao.org/contao selbst einzuwirken. Dort kann nur Leo aktiv werden.

**Comment by contaoacademy** [comment]
> Konntest Du das genau so mit einer selbst installierten Demo nachstellen?
Habe ich nicht getestet. Ich wollte es hier nur melden, damit sich jemand mit entsprechenden Rechten darum kümmert.
@leofeyer Kannst du dir das ansehen?

**Comment by cliffparnitzky** [comment]
Das Passwort ist falsch. Gleiches gilt für j.wilson.

**Comment by cliffparnitzky** [comment]
Fixed in 1132d38fb7066558f62f6bf650275973d2c8e9ff
