### ISSUE TITLE
404 nicht automatisch weiterleiten

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/official-demo#98]
Es wäre schön wenn die 404 nicht automatisch auf die Startseite weitergeleitet wird.

**Comment by may17** [comment]
Wo hast du das Problem festgestellt? Auf demo.contao.org geschieht das nicht allerdings wird da auch keine korrekte 404 angezeigt.

**Comment by Tastaturberuf** [comment]
In der Import-SQL ist `autoforward = 1` hinterlegt.

https://github.com/contao/official-demo/blob/7e03ab0f0ba0871af7471501e7d01846e2207696/src/templates/codv4.4.0_contao_4.9.1.sql#L528

**Comment by Tastaturberuf** [comment]
Hier sieht man es durchs Syntax-Highlighting nochmal besser.

![image](https://user-images.githubusercontent.com/1027521/82640958-d62bf600-9c0b-11ea-836a-264957039734.png)

**Comment by may17** [comment]
@cliffparnitzky @sascha-mueller spricht nichts dagegen oder?

**Comment by Tastaturberuf** [comment]
Auf der 404 fehlt dann noch ein Content-Element, im Moment ist da nichts.

**Comment by sascha-mueller** [comment]
> 
> 
> @cliffparnitzky @sascha-mueller spricht nichts dagegen oder?

Wogegen spricht nichts? Gegen ne eigene 404 Seite? Nein.

**Comment by cliffparnitzky** [comment]
Added with 1132d38fb7066558f62f6bf650275973d2c8e9ff

**Comment by Tastaturberuf** [comment]
Danke schön :)
