### ISSUE TITLE
Support Contao 4.10.x

### ISSUE THREAD

**Issue by fkaminski** [contao/official-demo#99]
Because of:
https://community.contao.org/de/showthread.php?79308-Contao-Demo-Installationsfehler&p=534257#post534257

**Comment by cliffparnitzky** [comment]
Generell wäre es nicht schierig, eine Demo auch für die 4.10 oder weitere anzufertigen. Allerings ist es mit dem heutigen Verfahren immer etwas aufwändig. Wenn man nun also immer ein Demo für die aktuelle LTS und parallel eine für den latest Release haben will, braucht man ständig 2 System. Soweit, so klar und eben auch nciht dramatisch.

Schwieriger ist wohl eher, die vernünftige Ablage der 2 Demos, die man dann hat.

Das aktuelle Versionskonzept sieht hier nur eine "forlaufende" Versionierung vor. Damit müsste man jetzt eine 4.6.0 anlegen, die für Contao 4.10 gilt ... das klingt für mich jetzt irgendwie nciht so toll.

Deshalb wäre hier mal die Frage, ob es vlt. auch generell übersichtlicher wäre, wenn man die jeweilige Demo Version gleich lautende zur Contao Verion macht, für die sie gilt.

@may17 @fkaminski @sascha-mueller @contao/official-demo Was denkt ihr darüber?

**Comment by may17** [comment]
Wir sollten darüber einmal sprechen um zu schauen wir damit umgehen.

**Comment by leofeyer** [comment]
> Deshalb wäre hier mal die Frage, ob es vlt. auch generell übersichtlicher wäre, wenn man die jeweilige Demo Version gleich lautende zur Contao Verion macht, für die sie gilt.

Auf jeden Fall. 👍🏻

**Comment by cliffparnitzky** [comment]
Ich hab mal einen ersten Entwurf getätigt. Mit dem Branch:  release/official-demo-for-contao-4.10.5

Darin dann ebenfalls eine SQL Datei `official-demo-for-contao-4.10.5.sql`.

- Das alles dann als Version 4.10.5 taggen wäre die exakte Verknüpfung zur minimal gültigen 4.10er Version. So hat man dann u.U. auf der Patch Stelle größere Sprünge. Außerdem wäre ein Fix innerhalb einer Patch Nummer von Contao dann nicht mehr möglich.
- Das als Version 4.10.0 getaggt bietet die Felxibilität das patchens und erzeugt eben keine Sprünge ... stelle aber nicht so den direkten Bezug zur Contao Version her

Was anderes gibt das Semantic Versioning wohl aber nicht her. D.h. eines von beidem wird man wohl machen müssen.

**Comment by may17** [comment]
Ich denke wir haben hier zwei unterschiedliche Dinge:

a) Ist die Benamung. Da finde ich cliffs Vorschlag gut. Zumindest wüsste der Konsument direkt Bescheid.
b) Ist der Aufwand der Veröffentlichung. Man muss immer zwei Systeme warten LTS und Latest. Im Grunde ja ähnliches Problem wie vor dem das Core Team steht. Nur das wir die sql Datei haben die so herrlich nicht Versionsfreundlich ist. Vielleicht sollten wir darüber nachdenken die sql über einen eigenen Prozess direkt zu installieren via Database Transactions. Ab 4.10 hilft da ggf die Migrations auch.

**Comment by sascha-mueller** [comment]
Die Benamung parallel zu Contao find ich auch gut. Allerdings würde ich die Patch-Version eher abhängig von unserem Fortschritt sehen, statt diese anhängig von Contao zu machen.

**Comment by fkaminski** [comment]
Zur Handhabung der .sql Dateien/Installation kann ich nichts sagen. Wenn dann habe ich bisher die .cto genutzt/importiert. 

Gibt es diesbezüglich (nur Layout/Theme) Pläne eurerseits? 
Denke da im ersten Schritte an Conato Version unabhängigen Umsetzungen via CSS ID/Klassen etc.. Also via vorgegebenen Namenskonventionen (BEM). Wenn die finale Namenskonvention steht könnte man dies evtl. auch über die Docs aufführen bzw. aktuell halten.

Im Anschluß daran evtl. die Umsetzung in Anlehnung an das [nutshell](https://github.com/ErdmannFreunde/euf_nutshell) Konzept (erdmann&freunde).
Die "Basis" Version kann dann hier versioniert und nach und nach erweitert (und f. Updates gezogen) werden . Weitere Layouts ergeben sich dann evtl. auf Basis dieser Version die kopiert bzw. via Sass überschrieben werden könnte. Vielleicht ergeben sich somit dann auch zukünftig mehere Layouts via PR*s auf dieser Basis. 

Wie gesagt dies "nur" Layout bezogen (ohne ind. Templates oder Erweiterungen)

**Comment by may17** [comment]
Bisher ist die Demo nicht als Startpunkt für neue Websites gedacht sondern nur zum spielen. Das zeigt auch der Blick auf die Lizenz.

Ziel der Demo war es damals Funktionen von Contao vorzustellen und auch etwas Hilfestellung zu geben. Das alles mit Bordmitteln ohne CSS Methodologie etc. damals noch mit dem Stylesheet Wizard (oder wie das Ding hieß)

Zudem wollten wir damals nicht den Themenherstellern Konkurrenz machen.

Wenn du eine COD 2.0 machen willst, fühl dich frei. Ich trete gerne alles ab was mit der Demo zu tun hat.

**Comment by cliffparnitzky** [comment]
Ich hab jetzt diese Version mit 4.10.0 getaggt. Sie ist zwar erst ab Version 4.10.5 verwendbar, aber mit der Patchnummer würde ich @sascha-mueller folgen ... ich hab doch in der Vergangenheit des öfteren mal nachjustieren müssen ... dass kann ich dann mit der dritten Stelle.

Das Ticket schließe ich dann.
